const categories = [
  { name: "Film & Animation", rate: 3 },
  { name: "Autos & Vehicles", rate: 4 },
  { name: "Music", rate: 2 },
  { name: "Pets & Animals", rate: 5 },
  { name: "Sports", rate: 1 },
  { name: "Short Movies", rate: 4 },
  { name: "Travel & Events", rate: 3 },
  { name: "Gaming", rate: 2 },
  { name: "Videoblogging", rate: 4 },
  { name: "People & Blogs", rate: 5 },
  { name: "Comedy", rate: 3 },
  { name: "Entertainment", rate: 2 },
  { name: "News & Politics", rate: 1 },
  { name: "Howto & Style", rate: 4 },
  { name: "Education", rate: 5 },
  { name: "Science & Technology", rate: 3 },
  { name: "Nonprofits & Activism", rate: 2 },
  { name: "Movies", rate: 4 },
  { name: "Anime/Animation", rate: 5 },
  { name: "Action/Adventure", rate: 3 },
  { name: "Classics", rate: 2 },
  { name: "Comedy", rate: 1 },
  { name: "Documentary", rate: 4 },
  { name: "Drama", rate: 3 },
  { name: "Family", rate: 2 },
  { name: "Foreign", rate: 5 },
  { name: "Horror", rate: 4 },
  { name: "Sci-Fi/Fantasy", rate: 2 },
  { name: "Thriller", rate: 3 },
  { name: "Shorts", rate: 1 },
  { name: "Shows", rate: 4 },
  { name: "Trailers", rate: 5 },
];

export default categories;
